---
apiVersion: extensions/v1
kind: Ingress
metadata:
  namespace: kubeapps
  name: kubeapps
  annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
spec:
  rules:
    - http:
        paths:
        - backend:
            serviceName: kubeapps
            servicePort: 80
          path: /kubeapps
